# --- CONFIGURACIÃ“N STARSHIP: ANDROID PRO ---

# 1. Estructura General
# Usamos dos lÃ­neas para que si la ruta es larga, tengas espacio para escribir.
add_newline = true

format = """
$directory\
$git_branch\
$git_status\
$java\
$kotlin\
$gradle\
$cmd_duration\
$line_break\
$character"""

# 2. El Prompt (La flechita)
[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[â¯](bold red)"
vimcmd_symbol = "[â®](bold green)" # Cambia si entras en modo Normal de Vim

# 3. Directorio (Rutas inteligentes)
[directory]
truncation_length = 3
truncation_symbol = "â€¦/"
style = "bold blue"
read_only = " ğŸ”’"

# 4. Git (Lo mÃ¡s importante)
[git_branch]
symbol = "ï˜ "
style = "bold purple"

[git_status]
style = "red"
conflicted = "ğŸ³"
ahead = "â‡¡${count}"
behind = "â‡£${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
untracked = "?${count}"
stashed = "ğŸ“¦"
modified = "!${count}"
staged = "+${count}"
renamed = "Â»${count}"
deleted = "âœ˜${count}"

# 5. Java & Android (Tu dÃ­a a dÃ­a)
[java]
symbol = "â˜• "
style = "red dim"
# Solo mostramos Java si hay archivos java en la carpeta
detect_extensions = ["java", "class", "jar", "gradle", "clj", "cljc"]

[kotlin]
symbol = "ğŸš€ "
style = "blue dim"

[gradle]
symbol = "ğŸ˜ "
style = "white dim"
disabled = false 

# 6. Utilidades
[cmd_duration]
min_time = 2000 # Solo muestra el tiempo si tarda mÃ¡s de 2s
format = "took [$duration]($style) "
style = "yellow"

[memory_usage]
disabled = true # Ahorramos recursos
